spring:
  application:
    name: stock

  data:
    mongodb:
      uri: ${MONGODB_URI:}
      database: ${MONGODB_DATABASE:stock_data}
      auto-index-creation: ${MONGODB_AUTO_INDEX:true}

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_STARTTLS_ENABLE:true}

jwt:
  secret: ${JWT_SECRET:}
  expiration: ${JWT_EXPIRATION:3600000}

gemini:
  apiKey: ${GEMINI_APIKEY:}
  model: ${GEMINI_MODEL:gemini-2.5-flash}

finnhub:
  apiKey: ${FINNHUB_APIKEY:}
