spring:
  application:
    name: stock

  data:
    mongodb:
      uri: "mongodb+srv://Ashutosh1503k:Ashutosh91639@cluster0.5c2av1i.mongodb.net/?appName=Cluster0"
      database: stock_data
      auto-index-creation: true


  mail:
    host: smtp.gmail.com
    port: 587
    username: ashutoshperso@gmail.com
    password: unby glye titu hhhs
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true


jwt:
  secret: "Rias_Akeno_DXD_jjk_sukuna_isekai_light_dark_knight_yagami_big_pom_pom_yu"
  expiration: 3600000

gemini:
  apiKey: AIzaSyAyz9IZLtXDHiLsljAmXlr29z7bE6BqocU
  model: "gemini-2.5-flash"

finnhub:
  apiKey: d42f6shr01qorler3e90d42f6shr01qorler3e9g